TennisForEveryone/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;

namespace TennisForEveryone.Models
{
    public partial class Schedule
    {
        [Column("ID")]
        public int Id { get; set; }
        public DateTime When { get; set; }
        public string Description { get; set; }
        public string CoachEmail { get; set; }
        public string Location { get; set; }
    }
}

TennisForEveryone/Models/ViewModel/ScheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TennisForEveryone.Models.ViewModel
{
    public class ScheduleViewModel
    {
        public string Schedule { get; set; }
        public string CoachName { get; set; }
        public int CoachId { get; set; }
        public string Email { get; set; }
        public DateTime ScheduleDate { get; set; }
    }
}

TennisForEveryone/Controllers/CoachesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TennisForEveryone.Data;
using TennisForEveryone.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace TennisForEveryone.Controllers
{
  
    public class CoachesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CoachesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        
        // GET: Coaches
        public async Task<IActionResult> Index()
        {
            ApplicationUser usr = await _userManager.GetUserAsync(HttpContext.User);
            var coachList = _context.Coach;

            if (usr != null)
            {
                var userIsCoach = false;
                foreach (var coach in coachList)
                {
                    if (usr.Email == coach.Email)
                    {
                        userIsCoach = true;
                    }
                }

                if (userIsCoach)
                {
                    var x = await _context.Coach.FirstOrDefaultAsync(c => c.Email == usr.Email);
                    List<Coach> caoch = new List<Coach>();
                    caoch.Add(x);
                    return View(caoch);
                }
            }
            return View(await _context.Coach.ToListAsync());
        }

       
        // GET: Coaches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coach
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coach == null)
            {
                return NotFound();
            }

            return View(coach);
        }

        [Authorize(Roles = "Coach, Admin")]
        // GET: Coaches/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Coach, Admin")]
        // POST: Coaches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Email,Biography,PhotoUrl")] Coach coach)
        {
            if (ModelState.IsValid)
            {
                _context.Add(coach);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coach);
        }

        [Authorize(Roles = "Admin, Coach")]
        // GET: Coaches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coach.FindAsync(id);
            if (coach == null)
            {
                return NotFound();
            }
            return View(coach);
        }

        [Authorize(Roles = "Admin, Coach")]
        // POST: Coaches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Email,Biography,PhotoUrl")] Coach coach)
        {
            if (id != coach.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(coach);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoachExists(coach.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(coach);
        }

        [Authorize(Roles = "Admin, Coach")]
        // GET: Coaches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coach
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coach == null)
            {
                return NotFound();
            }

            return View(coach);
        }

        [Authorize(Roles = "Admin, Coach")]
        // POST: Coaches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coach = await _context.Coach.FindAsync(id);
            _context.Coach.Remove(coach);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Coach")]
        public IActionResult MySchedules()
        {
            // GET current User
            var user = _userManager.GetUserName(User);

            // Query db to match all records with same CoachEmail
            var schedules = _context.Schedule.Where(m => m.CoachEmail == user);

            return View("MySchedules", schedules);
        }
        private bool CoachExists(int id)
        {
            return _context.Coach.Any(e => e.Id == id);
        }
    }
}

TennisForEveryone/Controllers/ScheduleMembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TennisForEveryone.Data;
using TennisForEveryone.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace TennisForEveryone.Controllers
{
    public class ScheduleMembersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ScheduleMembersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: ScheduleMembers
        public async Task<IActionResult> Index()
        {
            ApplicationUser usr = await _userManager.GetUserAsync(HttpContext.User);
            var data = _context.Schedule;
            var coachList = _context.Coach;
            var scheduleMembers = await _context.ScheduleMembers.ToListAsync();
            if (usr != null)
            {
                var userIsCoach = false;
                foreach (var coach in coachList)
                {
                    if (usr.Email == coach.Email)
                    {
                        userIsCoach = true;
                    }
                }


                if (userIsCoach)
                {
                    List<Schedule> coachSchedules = data.ToList().FindAll(s => s.CoachEmail.Equals(usr.Email));
                    List<ScheduleMembers> filteredMembers = new List<ScheduleMembers>();
                    foreach (var coachSchedule in coachSchedules)
                    {
                        List<ScheduleMembers> filteredMembersTemp = scheduleMembers.FindAll(sm => sm.ScheduleId == coachSchedule.Id);
                        filteredMembers.AddRange(filteredMembersTemp);
                    }
                    return View(filteredMembers);
                }
            }
            return View(scheduleMembers);
        }

        // GET: ScheduleMembers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleMembers = await _context.ScheduleMembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scheduleMembers == null)
            {
                return NotFound();
            }

            return View(scheduleMembers);
        }

        // GET: ScheduleMembers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ScheduleMembers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ScheduleId,MemberEmail")] ScheduleMembers scheduleMembers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(scheduleMembers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(scheduleMembers);
        }

        // GET: ScheduleMembers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleMembers = await _context.ScheduleMembers.FindAsync(id);
            if (scheduleMembers == null)
            {
                return NotFound();
            }
            return View(scheduleMembers);
        }

        // POST: ScheduleMembers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ScheduleId,MemberEmail")] ScheduleMembers scheduleMembers)
        {
            if (id != scheduleMembers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(scheduleMembers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduleMembersExists(scheduleMembers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(scheduleMembers);
        }

        // GET: ScheduleMembers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleMembers = await _context.ScheduleMembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scheduleMembers == null)
            {
                return NotFound();
            }

            return View(scheduleMembers);
        }

        // POST: ScheduleMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var scheduleMembers = await _context.ScheduleMembers.FindAsync(id);
            _context.ScheduleMembers.Remove(scheduleMembers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
               [Authorize(Roles = "Member")]
                // GET: ScheduleMembers/Enroll/5
                public async Task<IActionResult> Enroll(int? id)
                {
                    ApplicationUser usr = await GetCurrentUserAsync();
                    if (id == null)
                    {
                        return NotFound();
                    }
                    var schedule = await _context.Schedule.FindAsync(id);
                    if (schedule == null)
                    {
                        return NotFound();
                    }
                    ViewBag.userEmail = usr.Email;
                    return View(schedule);
                }


                    //POST: ScheduleMembers/Enroll/6
                    [HttpPost, ActionName("Enroll")]
                    [ValidateAntiForgeryToken]
                    public async Task<IActionResult> EnrollConfirmed([Bind("ScheduleId,MemberEmail")] ScheduleMembers scheduleMembers)
                    {
                        if (ModelState.IsValid)
                        {
                            _context.Add(scheduleMembers);
                            await _context.SaveChangesAsync();
                            return RedirectToAction("Index","ScheduleView");
                        }
                       return View(scheduleMembers);
                    }

        // GET /ScheduleMembers/Enrollments/5
        [Authorize(Roles = "Member")]
        public IActionResult MyEnrollments()
        {
            // GET Username
            var user = _userManager.GetUserName(User);

            // Query db records that match Username
            var schedules = _context.ScheduleMembers.Where(m => m.MemberEmail == user);

            return View("MyEnrollments", schedules);
        }
        private bool ScheduleMembersExists(int id)
        {
            return _context.ScheduleMembers.Any(e => e.Id == id);
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
    }
}

TennisForEveryone/Views/Schedules/Create.cshtml
@model TennisForEveryone.Models.Schedule

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Schedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="When" class="control-label"></label>
                <input asp-for="When" class="form-control" />
                <span asp-validation-for="When" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoachEmail" class="control-label"></label>
                <input asp-for="CoachEmail" class="form-control" />
                <span asp-validation-for="CoachEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TennisForEveryone/Views/Schedules/Delete.cshtml
@model TennisForEveryone.Models.Schedule

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.When)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.When)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoachEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoachEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TennisForEveryone/Views/Schedules/Details.cshtml
@model TennisForEveryone.Models.Schedule

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.When)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.When)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoachEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoachEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TennisForEveryone/Views/Schedules/Edit.cshtml
@model TennisForEveryone.Models.Schedule

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Schedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="When" class="control-label"></label>
                <input asp-for="When" class="form-control" />
                <span asp-validation-for="When" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoachEmail" class="control-label"></label>
                <input asp-for="CoachEmail" class="form-control" />
                <span asp-validation-for="CoachEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TennisForEveryone/Views/Schedules/Index.cshtml
@model IEnumerable<TennisForEveryone.Models.Schedule>

@{
    ViewData["Title"] = "Schedules";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Schedules</h2>

@if (User.IsInRole("Admin") || User.IsInRole("Coach"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.When)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CoachEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.When)
                </td>
                <td>
                    @if (User.IsInRole("Coach") || User.IsInRole("Admin"))
                    {
                        <a asp-controller="Coaches" asp-action="Schedules" asp-route-id="@item.Id">
                            @Html.DisplayFor(modelItem => item.Description)
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Schedules" asp-action="Details" asp-route-id="@item.Id">
                            @Html.DisplayFor(modelItem => item.Description)
                        </a>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CoachEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                @if (User.IsInRole("Admin") || User.Identity.Name == item.CoachEmail && User.IsInRole("Coach"))
                {
                    @if (item.When < DateTime.Now)
                    {
                        <td id="notgood">
                            <a class="btn btn-default" id="unavailable">Unavailable</a>
                        </td>
                    }
                    else
                    {
                        <td>
                            <a asp-controller="ScheduleMembers" asp-area="" asp-action="Enroll" asp-route-id="@item.Id" class="btn btn-success">Enroll</a>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    }
                }
                else
                {
                    @if (item.When < DateTime.Now)
                    {
                        <td id="notgood">
                            <a class="btn btn-default" id="unavailable">Unavailable</a>
                        </td>
                    }
                    else
                    {
                        <td>
                            <a asp-controller="ScheduleMembers" asp-area="" asp-action="Enroll" asp-route-id="@item.Id" class="btn btn-success">Enroll</a>
                        </td>
                    }
                }
            </tr>
        }
    </tbody>
</table>