TennisForEveryone/Controllers/AdminController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TennisForEveryone.Models;
using TennisForEveryone.Models.ViewModel;

namespace TennisForEveryone.Controllers
{

    //Controller for adding new roles
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
        }



        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                // We just need to specify a unique role name to create a new role
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                // Saves the role in the underlying AspNetRoles table
                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }
    }
}

TennisForEveryone/Controllers/ApplicationRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TennisForEveryone.Models;
using TennisForEveryone.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;

namespace TennisForEveryone.Controllers
{

    public class ApplicationRoleController: Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public UserManager<ApplicationUser> UserManager { get; }

        public ApplicationRoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }


        
        public IActionResult Index()
        {
            List<RoleViewModel> model = new List<RoleViewModel>();

            model = roleManager.Roles.Select(r => new RoleViewModel
            {
                RoleName = r.Name,
                Id = r.Id
            }).ToList();
            return View(model);
        }

        [HttpGet]
        // Get specific role to edit 
        public async Task<IActionResult> EditRole(string id)
        {
            var r = await roleManager.FindByIdAsync(id);

            if (r == null)
            {
                return NotFound();
            }

            var model = new RoleViewModel
            {
                Id = r.Id,
                RoleName = r.Name
            };
            //get all the associate users to the role -Sandipa
            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, r.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);
        }

        //Update role in database once user change/edit Role name -Sandipa
        [HttpPost]
        public async Task<IActionResult> EditRole(RoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                return NotFound();
            }
            else
            {
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }
        }


        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;
            var role = await roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = "Not found";
                return NotFound();
            }
            var model = new List<UserRoleViewModel>();
            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
          
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }
                model.Add(userRoleViewModel);
            }
            return View(model);

        }

       
        [HttpPost]
        /*Added Http post request method called ‘EditUsersInRole’ 
        to be able to assign roles to users. Such as Admin, Coach, Member.(Sandipa)*/
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                return View("NotFound");
            }
       
            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }


            return RedirectToAction("EditRole", new { id = roleId });
        }
    }
}

TennisForEveryone/Views/ApplicationRole/EditRole.cshtml
@model TennisForEveryone.Models.ViewModel.RoleViewModel

@{
    ViewData["Title"] = "EditRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>EditRole</h2>

    <form method="post">
        <div>
            <h3>Role Name</h3>
            @name
        </div>


        <div>
            <h3>User List</h3>
            <table>
                <thead>
                    <tr>
                        <th> User Name</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        @if (Model.Users.Any())
                        {
                            foreach (var user in Model.Users)
                            {
                                <td>
                                    @user
                                </td>
                            }
                        }

                        else
                        {
                            <td>No users in this role.</td>
                        }
                    </tr>
                </tbody>

            </table>
            <
        </div>
    </form>*@


<h1>Edit Role</h1>
<form method="post" class="mt-3">
    
    <div>
        <label asp-for="RoleName"></label>
        <input asp-for="RoleName" />
        <span asp-validation-for="RoleName" class="text-danger"></span>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div>
        <button type="submit" class="btn btn-primary">Update</button>
        <a asp-action="Index" class="btn btn-primary">Cancel</a>
    </div>
    <div class="card mb-3 mt-2">
        <div class="card-header">
            <h4>Users in this role</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">
                @if (Model.Users.Any())
                {
                    foreach (var user in Model.Users)
                    {
                        <h5 class="card-text">@user</h5>
                    }
                }
                else
                {
                    <h5 class="card-text">None at the moment</h5>
                }
            </h5>
        </div>
        <div class="card-footer">
            <a asp-action="EditUsersinRole" asp-controller="ApplicationRole" 
               asp-route-roleId="@Model.Id" class="btn btn-primary">Add or Remove Users</a>
        </div>
    </div>
</form>

TennisForEveryone/Views/ApplicationRole/EditUsersInRole.cshtml
@model List<TennisForEveryone.Models.ViewModel.UserRoleViewModel>
@{
    ViewData["Title"] = "EditUsersInRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var roleId = ViewBag.roleId;
}


    <form method="post">
           <div class="card mb-3 mt-2">
            <div class="card-header">
                <h4>Add or remove users from this roles</h4>
            </div>
            <div class="card-body">
                @for (int i = 0; i < Model.Count; i++)
                {
                    <div class="form-check m-1">
                        <input type="hidden" asp-for="@Model[i].UserId" />
                        <input type="hidden" asp-for="@Model[i].UserName" />
                        <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                        <label class="form-check-label" asp-for="@Model[i].IsSelected">
                            @Model[i].UserName
                        </label>
                    </div>
                }
            </div>
            <div class="card-footer">
                <input type="submit" value="Update" class="btn btn-primary"/>
                <a asp-action="EditRole" asp-route-Id="@roleId" class="btn btn-primary">Cancel</a>
            </div>
        </div>
    </form>

TennisForEveryone/Views/ApplicationRole/Index.cshtml
@model IEnumerable<TennisForEveryone.Models.ViewModel.RoleViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="top-buffer"></div>
<div class="panel panel-primary">
    <h2 class="panel-heading panel-head">Application Roles</h2>
    <a asp-action="CreateRole" asp-controller="Administration" class="btn btn-primary">Create Role</a>
    <div class="panel-body mt-3">
        <div class="top-buffer"></div>
        <table class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th>Role Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.RoleName </td>
                        <td>
                            <a asp-action="EditRole" asp-controller="ApplicationRole" asp-route-id="@item.Id" class="btn btn-success">View details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>